feat : 그룹 추가 기능 구현
CHZZK-Study/team-1-server pull request #5
Opened 2024-02-18 11:39 UTC by junslog

## 👀 관련 이슈

close #이슈번호

## ✨ 작업 내용

-

## 🙏 리뷰 요구 사항

-

## 📢 논의하고 싶은 내용

-

## 🎸 기타 사항

- [[링크]()]

2024-02-26 04:48 UTC, djc06048 commented on src/main/java/foxcord/group/dto/response/GroupResponse.java
> +    public static GroupResponse toDto(Group group) {
record의 경우 생성자 자동으로 만들어주는 것으로 알고 있는데
@junslog  toDto 의 역할은 뭔가요?

2024-02-26 05:50 UTC, k0duck reviewed
수고하셨습니다🫡

2024-02-26 05:50 UTC, k0duck commented on src/main/java/foxcord/group/entity/Group.java
> +@Table(name = "\"group\"")
GROUP이 예약어라 따로 이름을 따옴표로 감싸주신거 같은데,
개인적인 생각으로는 정말 불가피한 경우가 아니라면 아예 예약어를 사용하지 않는 것이 좋다고 생각합니다.

따라서 `groups`로 사용하거나, 아예 명칭을 디스코드에서 사용하는 서버`server`라고 변경하는게 어떨까하는 생각이 들었는데 어떻게 생각하시는지 궁급합니다!
(후자의 경우는 이미 많은 길을 온거 같아 변경이 매우 번거로워질 것 같아 전자가 낫지 않을까 싶긴 하네요...ㅎ)

2024-02-26 05:50 UTC, k0duck commented on src/test/java/foxcord/domain/group/GroupTest.java
> +        String updateGroupName = "정맒멋쟁이그룹";
오탈자 발견했습니다!
'정맒'을 의도하신거라면 물러가겠습니다.🤫

2024-02-26 05:50 UTC, k0duck commented on src/test/java/foxcord/domain/group/GroupTest.java
도메인 로직 테스트와 레포지토리 로직 테스트가 혼재되어 있는 것 같아요.
when절에 테스트 타켓이 되는 객체가 사용되는데, 
`generateGroup`과 `updateGroup`을 보면 Group 클래스의 로직을 테스트하고 있고, `deleteGroup`은 GroupRepository 클래스의 로직을 테스트하고 있어요.

GroupRepository의 경우 현재는 기본 JpaRepository 기능만을 사용하고 있기 때문에 테스트 코드를 작성할 필요는 없다고 생각하고,
만들어준 서비스 클래스를 대상으로 테스트 코드를 작성해주는게 좋을 것 같다고 생각하는데 어떻게 생각하시나요?!

현재 해당 클래스에서는 GroupService를 전혀 사용하고 있지 않은데 의존성 주입을 해주신 이유도 궁금합니다!

2024-02-26 11:39 UTC, junslog commented on src/main/java/foxcord/group/entity/Group.java
> +@Table(name = "\"group\"")
맞습니다. 찾아보니 group이 MySQL의 예약어에 들어있었습니다!

Groups로 바꿔주는 것이 더 나을 것 같습니다,
아니면 Community 라는 네이밍도 괜찮을 것 같은데, @k0duck 님은 어떻게 생각하시나요?

2024-02-26 11:45 UTC, junslog commented on src/test/java/foxcord/domain/group/GroupTest.java
아, 도메인 로직 테스트와 레포 로직 테스트를 혼재하게 두면
테스트 자체의 통일성이 없겠군요! 이 부분 생각치 못했는데, 말씀해주셔서 감사합니다. 
분리한 뒤에 다시 커밋해야겠습니다!

테스트 내용이 JpaRepository의 기본 기능이라 말씀하신대로 
테스트 필요성 까진 없어보입니다.

GroupService를 거쳐서 GroupRepository의 기능을 호출하는 식으로 테스트를 짠다고 생각하고
내용을 누락한 것 같습니다! 추가될 Repository 및 Service 테스트로 해당 의존성은 옮기는 게 좋을 거 같네요!!

2024-02-27 12:52 UTC, k0duck commented on src/main/java/foxcord/group/entity/Group.java
> +@Table(name = "\"group\"")
그런데 이미 API에 group이라고 작성된 부분이 많아서ㅜㅜ Community로 변경하면 많은 곳을 손봐야 할 것 같아요....🥲
아무래도 지금으로써는 groups로 처리하는게 가장 편안하지 않을까 싶습니다!

2024-02-29 08:31 UTC, k0duck requested changes
group 테이블명이랑 테스트 코드만 수정되면 머지해도 될 것 같습니다!😊

2024-02-29 08:31 UTC, k0duck commented on src/test/java/foxcord/domain/group/service/GroupServiceTest.java
> +        groupRepository.deleteById(groupId);
GroupServiceTest에서 groupService의 `removeGroup()` 기능에 대한 테스트 코드를 작성해주신거 같은데,
현재 `deleteGroup()` 테스트 메서드는 groupRepository의 `deleteById()`를 테스트하고 있어요..!

2024-03-04 11:25 UTC, junslog commented on src/test/java/foxcord/domain/group/service/GroupServiceTest.java
> +        groupRepository.deleteById(groupId);
[cde93b3](https://github.com/CHZZK-Study/team-1-server/pull/5/commits/cde93b3984d4b34a94a81d83535f7d27459d0763)

2024-03-04 12:18 UTC, merged